# Generated by Django 4.0.1 on 2024-04-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('total', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveBigIntegerField()),
                ('status', models.PositiveIntegerField(default=0, help_text='Status of product in cart')),
                ('product_type', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Carts',
                'db_table': 'carts',
            },
        ),
    ]
