# Generated by Django 4.0.1 on 2024-04-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='status',
            new_name='product_status',
        ),
    ]
