# Generated by Django 4.0.1 on 2024-04-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_status_cart_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
