# Generated by Django 4.0.1 on 2024-04-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_price',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
    ]
