# Generated by Django 4.0.1 on 2024-04-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('total', models.PositiveBigIntegerField()),
                ('status', models.PositiveIntegerField(default=0)),
                ('payment_status', models.PositiveIntegerField(default=0)),
                ('payment_method', models.PositiveIntegerField(default=0)),
                ('shipping_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
    ]
