# Generated by Django 4.0.1 on 2024-04-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
