# Generated by Django 4.0.1 on 2024-04-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_shipment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'verbose_name_plural': 'Shipments'},
        ),
        migrations.AlterModelTable(
            name='shipment',
            table='shipments',
        ),
    ]
